# Generated by Django 3.2.12 on 2023-06-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_doc',
            field=models.ImageField(default='default_image.jpg', upload_to=''),
        ),
    ]
