# Generated by Django 3.2.12 on 2023-06-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_company_company_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_doc',
        ),
    ]
